Revert "Merge pull request #721 from jacekkopecky/copy-from-line-above"
This reverts commit 65b465d7b38cd926579aca0ab95e76ccee6e2206, reversing
changes made to cccd4a0dd08cee3a042886e424e317e612242b1a.

Getting some weird `apm test` errors that bisect to this commit
but I don't see why.

        TypeError: Cannot read property 'activateResources' of null
        (spec/insert-mode-spec.coffee:8:12)
        etc